# frozen_string_literal: true
# A sample Gemfile
#
# install:  % bundle install --path bundle/vendor
#
source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-reloader'
gem 'unicorn'
gem 'mysql2'
gem 'bcrypt'
gem 'bson_ext'
gem 'rack'
gem 'twilio-ruby'
gem 'mail'
gem 'padrino-helpers'
gem 'padrino-mailer'
gem 'haml'
gem 'actionmailer'
gem 'commonmarker'
gem 'redcarpet'
gem 'sinatra-cross_origin'