create table kouhou.admins (
       id                 int  auto_increment not null,
       uuid               char(36)            not null,
       email              text                not null,
       first_name         varchar(12)         not null,
       last_name          varchar(12)         not null,
       permit_user        int                 not null default 0,
       permit_bingo       int                 not null default 0,
       permit_proj        int                 not null default 0,
       permit_news        int                 not null default 0,
       permit_qr          int                 not null default 0,
       permit_admin       int                 not null default 0,
       access_key         char(36)            ,
       passhash           varchar(512)        not null,
       token              text                not null,
       token_expire       datetime            not null,
       status             int                 not null default -1,
       del_flg            int                 not null default 0,
       ena_flg            int                 not null default -1,
       reg_time           timestamp           not null default current_timestamp,
       upd_time           timestamp           not null default current_timestamp on update current_timestamp,
       primary key(id)
 );
